### ISSUE TITLE
Input.select: Allow styling of dropdown-"arrow"

### ISSUE THREAD

**Issue by manuscrypt** [mdgriffith/stylish-elephants#10]
![image](https://user-images.githubusercontent.com/19311687/34794215-4932d22e-f64e-11e7-81eb-360411c718ba.png)

**Comment by mdgriffith** [comment]
`Input.select` got deprecated in the latest release.  I go over the reasoning here: https://github.com/mdgriffith/stylish-elephants/blob/5.0.0/v5-Alpha-2-changes.md

Long story short, you can craft an `Input.select` manually now, which give you complete contorl on how it shows up.
