### ISSUE TITLE
Can't get layout to fill viewport height

### ISSUE THREAD

**Issue by j-panasiuk** [mdgriffith/stylish-elephants#12]
I want to have page layout with fixed-size header + content stretching to fill the rest of viewport.
It seems that v5 is missing equivalent of v4 `viewport` function?
https://ellie-app.com/j76WpmvSRa1/0

**Comment by mdgriffith** [comment]
Hey!

Thanks for reporting this, I figured out what was going on.

Basically there should be no need for `viewport` in v5.  Once I release the patch I'm working on your code should work as-is.

**Comment by j-panasiuk** [comment]
Yes, that was the idea

**Comment by mdgriffith** [comment]
Right, basically the minimum height should be "fill the viewport", though you could force it to overflow and get historical `layout` behavior.

**Comment by mdgriffith** [comment]
Should be fixed in `v4` of stylish-elephants
