### ISSUE TITLE
`toHtml` is missing

### ISSUE THREAD

**Issue by akoppela** [mdgriffith/stylish-elephants#15]
In `v4` there is `toHtml` function. Which is missing in `v5`.

**Comment by mdgriffith** [comment]
Hmm, yeah I might add something like that.  What are you using it for?

The only use for it right now would be to avoid embedding the static stylesheet that style-elements embeds when you have multiple instances of style-elements in an app.

**Comment by akoppela** [comment]
I think that it maybe useful when I want to check `style-elements` from existing code base. When I was thinking how to do it I was looking for `toHtml` function. But then I found that there is `layout` for it.
I was using it here: https://github.com/akoppela/elm-logo/blob/master/examples/Basic.elm#L25

So maybe it's not an issue in the end.

**Comment by folkertdev** [comment]
I'm using style-elements to render templates for a static site generator - and would like to keep doing that. 

Many templating languages allow nested templates, so for instance I have a file for a single row, and then another file for the full table. Currently, every row would put the full css sheet into the output. 
(I assume this would compress well, but it's clearly not great). 

So ideally I could render just the html with elm-static-html-lib and then include the stylesheet once per page/in a separate css file.

**Comment by mdgriffith** [comment]
In the latest release you can do `layoutWith [ noStaticStyleSheet ] ..`
