### ISSUE TITLE
Provide helper functions for `paddingTop`, `borderTop` and friends.

### ISSUE THREAD

**Issue by akoppela** [mdgriffith/stylish-elephants#17]
It's now possible only to set all values with `padding`/`Border.width` or XY values with `paddingXY`/`Border.widthXY` or each value with `paddingEach`/`Border.widthEach`. But If I want to set only `paddingTop`/`Border.widthTop` I would need to use following.
```
paddingTop x =
    { bottom : 0, left : 0, right : 0, top : x }
```
It would be nice to have helper functions fro it out of the box.

One thing to consider, that it should be possible to stack them. E.g. `[ paddingTop 10, paddingBottom 20 ]`.

**Comment by kuon** [comment]
Yeah, and specific should win over generic. For example:

`padding 10, paddingBottom 20`

should set top, left and right to 10 and bottom to 20.

**Comment by mdgriffith** [comment]
I'm hesitant to do this because I'm not sure the overriding behavior is the best.  I much prefer it just being explicit, where the padding model is defined in one attribute.

You could mock something up that effectively does this though.  Something like:

```elm
-- Your own helper functions
type alias Edges =
    { bottom : Int
    , left : Int
    , right : Int
    , top : Int
    }


all i =
    { bottom = i
    , left = i
    , right = i
    , top = i
    }


top i edges =
    { edges | top = i }

{- Then in the view -} 
view = 
    el 
        [ paddingEach
            ( all 0
                |> top 10
            )
        ]
        (text "With borders")
```

**Comment by akoppela** [comment]
I see your point. Yes it make sense for me. It's much easier to maintain the code where you know for sure that if there is a padding on the element then there is only one attribute which is responsible to set it.
