### ISSUE TITLE
Is inlineStyle comming back?

### ISSUE THREAD

**Issue by kuon** [mdgriffith/stylish-elephants#19]
If not, how to workaround it? Using attribute?

**Comment by mdgriffith** [comment]
Yeah, it won't be coming back.  You'll have to use `attribute` to mimic it, though, I do want to collect cases where people are using `attribute`.   I know one of them is animation which generally uses inline styles.

The ultimate goal of this library is to not be completely bound to html semantics.

**Comment by kuon** [comment]
I'll open other issue when I notice some missing styles I fixed with `inlineStyle` then.
