### ISSUE TITLE
How to center background image

### ISSUE THREAD

**Issue by kuon** [mdgriffith/stylish-elephants#20]
How can I center a background image, equivalent of:

```
            ( "background-image", "url(" ++ url ++ ")" )
            , ( "background-size", "cover" )
            , ( "background-position", "50% 50%" )
```

**Comment by mdgriffith** [comment]
Can you use `behind` and `image` instead?

**Comment by kuon** [comment]
If the size and ratio of the source image is unknown, no.

**Comment by mdgriffith** [comment]
You sure?  This worked for me:

```elm
el
    [ width fill
    , height (px 200)
    , behind True <|
        decorativeImage
            [ width (px 200)
            , height shrink
            , center
            ]
            { src = "https://placeimg.com/640/420/animals/grayscale" }
    ]
    (text "Some content")

```

**Comment by kuon** [comment]
This won't crop the image. The idea is to crop the image from the center, like so: https://codepen.io/anon/pen/dJraZj

**Comment by mdgriffith** [comment]
Ah, so something like this?

```
el
    [ width fill
    , height (px 200)
    , behind True <|
        el [ clip, width (px 200), center ] <|
            decorativeImage
                [ height shrink
                , center
                ]
                { src = "https://placeimg.com/640/420/animals/grayscale" }
    ]
    (text "Some content")
```

**Comment by kuon** [comment]
Yes, but the image must be zoomed in if it's too small. If you set the width to `(px 800)` it doesn't work anymore.

**Comment by kuon** [comment]
Actually, `background.fittedImage` could simply center the image.

**Comment by kuon** [comment]
By current workaround, using `Background.fittedImage` with:

```css
[class^="bg-fitted-image"], [class*=" bg-fitted-image"] {
  background-position: center !important;
}

```

**Comment by mdgriffith** [comment]
Good point, I actually landed in a similar place and made the default for both `image` and `fittedImage` to be centered.  

I was actually debating renaming the functions:

`image` -> `naturalImage`
`fittedImage` -> `image`

Because fittedImage seems to be a better default.

**Comment by kuon** [comment]
I agree about `fittedImage` -> `image` as anyway it's not fit but fill, fit is when the image is downsized to fit and black borders are added if the ration of the container is not the same.

I think it would be better to have `image` which would be `background-size: cover; background-position: center;` and `imageWith` with an option argument to set both the size and the position. It would be a more complicated API, but I think the "cover this container with an image" is the majority of usages, while other usage would be more context dependent and having control over size and position and repeat would be a requirement. We could also name `imageWith` to `pattern` with options to control it.

**Comment by mdgriffith** [comment]
Background images are now default to being centered.  No renaming has happened, but I may come back to this.

**Comment by kuon** [comment]
I think a renaming would be good, tracked in separated issue https://github.com/mdgriffith/stylish-elephants/issues/52
