### ISSUE TITLE
Custom event handler

### ISSUE THREAD

**Issue by kuon** [mdgriffith/stylish-elephants#21]
I noticed that `Event.on` is gone. How should I attach a custom event handler?

**Comment by mdgriffith** [comment]
You should be able to add one using `attribute` and constructing an event handler using the `Html` library

**Comment by kuon** [comment]
Don't you think the library should keep `on` as a helper function?

**Comment by mdgriffith** [comment]
So, my inclination is the same as for other attributes, that I'd love to capture when people are using `attribute`, even for something like `on` for and support them more directly if it makes sense.

Specifically, I'd love for this library to eventually be able to compile to native android or iOS apps, and I don't think the `on` pattern with a json decoder and event name would translate directly.
