### ISSUE TITLE
Font weight is not applied in paragraph

### ISSUE THREAD

**Issue by kuon** [mdgriffith/stylish-elephants#23]
The following code:

```elm
         El.paragraph
            [ El.padding 40
            , Font.center
            , Font.weight 600
            ]
            [ El.text model.errorMessage ]
```

Don't apply the font weight to the inner text nodes.

Generated HTML looks like:

```
<p class=" se paragraph pad-40-40-40-40 text-center font-weight-600">
<div class="se text width-content height-content">error</div>
</p>
```

The problem is that the inner div has the `se` class, which will override the font weight.

The workaround is to wrap the text element with an `el` and set the weight on it, like so:

```elm
         El.paragraph
            [ El.padding 40
            , Font.center
            ]
            [ El.el [ Font.weight 600 ] (El.text model.errorMessage)
            ]
```

I think it is expected to be able to set the weight directly on the whole paragraph.

**Comment by mdgriffith** [comment]
Makes sense, I've adjusted the stylesheet so that this is the case in the next release.

**Comment by passiomatic** [comment]
Not sure if this is related but I've noticed that `Font.weight` is ignored in `Element.text` too. `Font.bold` works fine.

**Comment by kuon** [comment]
As long as we can set font weight for `100, 200, 300, 400, 500, 600, 700, 800, 900` I'm fine.

This is a bit unrelated, but do you plan to support `lighter` and `bolder` ?

**Comment by mdgriffith** [comment]
No `lighter` or `bolder` because I generally want to stay away from things that are relatively defined, but we will have all the weights you mentioned:

```
Font.heavy -- 900
Font.extraBold -- 800
Font.bold -- 700
Font.semiBold -- 600
Font.medium -- 500
Font.regular -- 400
Font.light -- 300
Font.extraLight -- 200
Font.hairline -- 100
```

**Comment by mdgriffith** [comment]
Fixed in latest release!
