### ISSUE TITLE
Element level opacity etc

### ISSUE THREAD

**Issue by adrianroe** [mdgriffith/stylish-elephants#24]
As discussed in Slack, there are a few attributes it would be helpful to set at an element level (such as opacity and mouseOverOpacity) that it would be helpful to have explicit functions to set, without having to resort to just calling attribute

**Comment by kuon** [comment]
I would like to see opacity and transform, with hover too. I use hover transform sometimes to make hover effects.

**Comment by mdgriffith** [comment]
Present in the new version as `alpha` :)
