### ISSUE TITLE
When there are multiple calls to the layout function, ".es" styles in subsequent layout calls override styles for elements in previous layout calls

### ISSUE THREAD

**Issue by neurodynamic** [mdgriffith/stylish-elephants#26]
I'm applying padding to a column and the generated `pad-10-10-10-10` class's styling is overridden by the `se` class's zero-padding.

**Comment by mdgriffith** [comment]
Hmm, I'm not seeing this.  When I test out a column with padding it shows correctly.  Are you on `v4` of the alpha?

**Comment by neurodynamic** [comment]
Yup. Upon further investigation, I think the issue may be that I'm calling the `layout` function twice on the page, so the second call creates a style tag that overrides those in the first.

Unless there's reason not to, I think this could be fixed by targeting `.se.pad-10-10-10-10` instead of just `.pad-10-10-10-10` in the css?

**Comment by neurodynamic** [comment]
Yup, definitely the issue. If I take out the other `layout` call the problem goes away.

**Comment by mdgriffith** [comment]
Oh, interesting, yeah I could see how that would be an issue.

I'll add `.se` to the generated style class names, thanks!
