### ISSUE TITLE
Do not import external resources

### ISSUE THREAD

**Issue by kuon** [mdgriffith/stylish-elephants#29]
I noticed that SE imports `Source Sans Pro` from google font.

I think it should not import anything by default, I am deploying my elm app in a sensitive environment, and this will get my app rejected by the security team.

**Comment by mdgriffith** [comment]
Uh, it does?

I don't believe SE is doing any font importing by default.  The default font is Open Sans, but there's no call to google fonts unless I'm missing something.

**Comment by kuon** [comment]
My bad, it was actually elm-reactor. I was doing some testing and noticed it, I was too quick to think it was SE fault.

It seems someone else is complaining (for another reason) about it, so for reference:

https://github.com/elm-lang/elm-reactor/issues/216
