### ISSUE TITLE
Shadow is always innerShadow

### ISSUE THREAD

**Issue by martindlarsson** [mdgriffith/stylish-elephants#34]
Using Border.shadow results in css with inset on box-shadow. Both innerShadow and shadow in Border.elm has inset = True

https://github.com/mdgriffith/stylish-elephants/blob/36ff207bb144cf8b92c6a0a9be45032220752723/src/Element/Border.elm#L191

Thanks for an awesome package! Keep up the good work

**Comment by mdgriffith** [comment]
Thanks for the issue!  This is fixed in the latest release :)
