### ISSUE TITLE
Option to set focus style for an input

### ISSUE THREAD

**Issue by kuon** [mdgriffith/stylish-elephants#43]
SE only support one global `focusStyle` for all inputs, but I have some inputs in my header that need specific styling when focused.

I was thinking about it, and I think we should be able to have more control over focused items. For example, you might want `transform` when focused.

Maybe something like this:

`el [color Color.red, focused [color Color.blue] ] ...`

Basically, the `focused` attribute would take a list of attributes applied on focus.

`focused: List (Attribute msg) -> Attribute msg`

I just thought about the requirement of applying focus style, not really of the implementation details.

**Comment by mdgriffith** [comment]
This should be covered in the latest release, thanks :)
