### ISSUE TITLE
'OnClick' Event stops working with 'inFront' on root Element (display:fixed)

### ISSUE THREAD

**Issue by rubas** [mdgriffith/stylish-elephants#45]
As soon as I position any element `inFront` the `onClick` Event all other elements is not working anymore. 

It doesn't matter where the „inFront“ Element is exactly positioned.

See this example: https://ellie-app.com/dZ3d2r9n9a1/2

After the first click, there is a simple Element added  `inFront` at the bottom of the page. The button stops working.

```
[ inFront model.status 
    (el
      [ width fill, Area.footer, alignBottom, Border.width 2]
      (text "Now, there is an element inFront. `onClick` Event doesn't work anymore:(")
  )
 ]
```

**Comment by kuon** [comment]
In your example, your element covers the whole page. That's why the button stops working, the element is in front of it.

**Comment by rubas** [comment]
Yes, that is the issue, but it shouldn't cover the whole page as it only a 1 line  `el` at the bottom of the page.

Do you have a solution for the example?

**Comment by kuon** [comment]
The `inFront` places an element at the front of the element you put it on, I think this is normal behavior.

You need to place your footer without using `inFront` as it should not be in front of the button.

**Comment by rubas** [comment]
It relates to your ticket #14.

To have something `display:fixed` I have to add it as `inFront` of the root element and this blocks all other elements.

*Use Case*
- Create a navigation bar with `display:fixed` at the bottom of the screen

**Comment by kuon** [comment]
I get it now. Well I checked the result on Ellie, and `display: fixed` is not used, so it seems that what @mdgriffith said in #14 is not applicable here, but I don't know why.

**Comment by mdgriffith** [comment]
Ah, yeah it's because there's an intermediate element that has width/height 100% in the case of InFront.  I've fixed it so that pointer events will pass through.

**Comment by mdgriffith** [comment]
This is fixed in the most recent release: https://ellie-app.com/dZ3d2r9n9a1/2
