### ISSUE TITLE
Rename Element.empty

### ISSUE THREAD

**Issue by kuon** [mdgriffith/stylish-elephants#71]
The previous behavior of `Element.empty` was to render an empty container.

The new behavior is to render nothing. I think it can cause confusion as migrated code behavior might change (DOM diffing might lose focus...).

I suggest to rename `empty` to `nothing` or `none`. We can keep `empty` too, but it's behavior need to be adjusted to generate an empty node.

**Comment by mdgriffith** [comment]
Makes sense!  I renamed it `none` in `6.0.0` to be similar to other libraries like `Sub.none`, `Cmd.none`.
