### ISSUE TITLE
Discussion about Color type

### ISSUE THREAD

**Issue by kuon** [mdgriffith/stylish-elephants#76]
As the `Color` module is going away with `0.19`. I think SE should use a type alias for `Color`.

`type alias Color = (Float, Float, Float, Float)  -- (r, g, b, a) normalized 0.0 -> 1.0`

The rational behind a public type alias is that we can easily write our own color functions without having to create a new type or convert functions (if `Color` was an opaque type like the current elm one is).

Having normalized floats makes math a lot easier. The alternative is the `(Int, Int, Int, Float)` format which is the `HTML` format is a bit weird as it uses a mix of non normalized and normalized values. Float values also support possible 10bit colors.

A tuple is easier to use than a record (shorter to write), and I think the `RGBA` order is quite ubiquitous, I don't think it would be open to confusion.

**Comment by mdgriffith** [comment]
Thanks, yeah I do have a plan for when `Color` is removed from core, which is similar to what you're proposing.  Basically standardizing an interop color data structure that isn't tied to one package.

I do like the idea of normalizing each channel and having the rendering as `Int` be a CSS rendering concern.  The only issue is that so many color tools show channel values as 0-255.  Not sure if that's the largest concern though.  Could be solved with a convenience function.

I have a module and a write up on this that I'll share in this issue later today.

**Comment by kuon** [comment]
`0-255` is really tied to historical concerns (8bit...), I think using floats is the best choice for a modern library, with a few conversion function it will be a breeze to use. The most important one is parsing the hex syntax `#4f8a93` every tool uses this when copy/pasting.

**Comment by mdgriffith** [comment]
Yeah, I agree there's no reason to use 0-255, only history.

So, here's what I sketched out a bit ago (and changed to normalized floats just now).  https://github.com/mdgriffith/elm-color

I did land on using a record instead of a tuple, as tuples above 3 are going away in 0.19.  Also a record helps a little bit with regard to "primitive blindness".   You can still define a color easily using the `rgb 0 0 0` function though, so, I don't believe we lose anything :)

**Comment by kuon** [comment]
I guess a record is fine. I would keep function like `mix` out of the library, to encourage people to use a library in a proper color space, knowing the result it would produce. And have only conversion/creation/serialization function inside the core lib.

I have a color parse function in my app, I'll just do what's needed to extract it and make it open source. It handles quite a few  formats. I'll make a PR on your other repository.

**Comment by kuon** [comment]
I extracted the Parse module here:

https://github.com/kuon/elm-color/commit/48aeb060526840b47604c08bdd67f2e543591663

I wrote a few tests to ensure it was working with your implementation, I also fixed the `hsl` constructor for normalized floats.

I renamed the module to `Color2`. When elm `0.19` hits, I'll make a pull request with the proper `Color` module name.

**Comment by mdgriffith** [comment]
Great!

So, one thought that I'm wondering is do we need parsers beyond the hex parser?

Probably the usecase is going to be copying over colors from existing style-sheets or SASS/LESS, and if they have something like `rgb(0,15,25)`, it would be pretty easy to transform that into `rgb 0 15 25` using just your text editor.

Basically I agree with your original point that this package should be as concise as possible :)

**Comment by kuon** [comment]
In my current app I have some colors coming from WYSIWYG editors and all browsers generate different css value depending on their mood, that's why I support all format. I agree the package should be concise, and thinking about it, I wonder if a bare datastruct package wouldn't be even better (just the type, the ` rgba` constructor and one accessor for each channel). The thing is, even the `hsl` constructor is somehow opinionated, why not `hsv`?

We could instead have a set of libraries, the core one, with just the type and the `rgba` functions, which shouldn't change in a long time. A stable core. Then we create a lib for parsing and serialization (`css: String -> Color`  `toCss: Color -> String`). One for color mixing and one per color space (like the HSLuv one I wrote).

I think it would be good to have @rtfeldman position on this, as he uses colors in `elm-css`.

**Comment by kuon** [comment]
For the color caching, in my code, I have a lot of dynamic colors, I'm caching the colors in my model as a theme record I guess I would have to convert those colors to element color but I still need to access the color itself, so the `Element.Color` type will need an accessor.

**Comment by mdgriffith** [comment]
Yeah, in general it would mean you'd have to convert `{r,g,b}` records to `Element.Color` to use them.

For storing dynamic colors, I think you'd be fine just storing them as you are now and only render them to an `Element.Color` at the last minute.

How can contrast not just be done in rgb space?  If every colorspace can be translated to rgb and we can calculate contrast between any two rgb colors, then we'd have contrast calculations for everything, right?

**Comment by kuon** [comment]
@mdgriffith I wasn't clear, you can compute lightness with `0.299 * R + 0.587 * G + 0.114 * B` (per https://www.w3.org/TR/AERT/#color-contrast) but for accessibility we need more tools, like given a source color, compute a color with enough contrast, taking into account color blindness... The accessibility function might grow quickly depending on user needs. I think this should stay out of the core lib.

I also found a few other ways to compute the lightness with RGB https://stackoverflow.com/questions/596216/formula-to-determine-brightness-of-rgb-color#596243

**Comment by kuon** [comment]
Moved to https://github.com/avh4/elm-color/issues/3
