### ISSUE TITLE
Independent column width for `table`.

### ISSUE THREAD

**Issue by jhf** [mdgriffith/stylish-elephants#85]
Currently the table forces all columns to have the same width, and that greatly reduces their practical value, for me at least.
This is demonstrated with SE 6.0.2 here - "https://ellie-app.com/dxbb7CdpBa1/7",
and with the previous SE 5 here - https://ellie-app.com/h8K69XBTLa1/18

![image](https://user-images.githubusercontent.com/18099/39718938-0d00c130-5238-11e8-9ba8-ef30e84d89fd.png)

**Comment by mdgriffith** [comment]
Hey, I finally had a chance to look at this.  When I take a look at both ellies, they both look basically the same except for line height, so I'm not entirely sure what I should be seeing.

That being said, I think it could be pretty easy to add some control over column width. I'm toying with something like this:

```elm
   Element.table []
        { data = persons
        , columns =
            [ { header = Element.text "First Name"
              , width = px 100
              , view =
                    (\person ->
                        Element.text person.firstName
                    )
              }
            , { header = Element.text "Last Name"
              , width = fill
              , view =
                     (\person ->
                        Element.text person.lastName
                     )
              }
            ]
        }

```

Would that address your usecase?

**Comment by jhf** [comment]
I think that would work - however - I think that by having a fixed column width by default is a bit strange, I would expect that each column would only occupy the space required by the content.

The two examples just demonstrate that the problem is the same in both SE 5 and 6.

**Comment by mdgriffith** [comment]
Hmm, I'm still a little confused by what you mean.  Both columns are set to `1fr` by default, which means they will fill the space and shrink if the content allows.  I'm currently seeing this:

<img width="312" alt="screen shot 2018-06-06 at 5 59 52 pm" src="https://user-images.githubusercontent.com/3045469/41067451-a4975918-69b3-11e8-952a-33cecf9ad177.png">

And then if I resize the window I see this, showing the smaller content shrinking:

<img width="171" alt="screen shot 2018-06-06 at 6 02 59 pm" src="https://user-images.githubusercontent.com/3045469/41067511-e60773b0-69b3-11e8-825c-31e29ea23d39.png">

Are we seeing browser differences?  I'm testing on chrome + firefox on OSX.
