### ISSUE TITLE
Newlines not working in Element.multiline

### ISSUE THREAD

**Issue by jxxcarlson** [mdgriffith/stylish-elephants#96]
Something changed in `stylish-elephants 7.0.0` (installed with `elm install mdgriffith/stylish-elephants`).  All text is now wrapped, but as far as I can tell, newlines are mapped to spaces — separation into paragraphs is lost.  Also, when I try to fix the text by entering `RETURN`, the visual result is a space. Used the ahem latest binary to compile.

**Comment by mdgriffith** [comment]
Fixed with `white-space: pre-wrap` in the release candidate.  Thanks!
